language: python
python:
- "3.6"
services: docker
env:
  global:
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=telephoneorg
  # DOCKER_PASS
  - secure: "jH8BW9v76umQKxJ8I+yRza1JvdERGTr1Rs1Ea3DmT163RI8QTZ8gDjguWIFP8wmuvqG5PT6ndq1Jq7wM0pUewjQA49T+1JGlz27HP98E2C1luBCVyTjkrGP0iAan4GfmAXYScG8idnPOPaKqbOAe9sSVhVSiSOTefTvU3ord64GG3A0xKw/q2OG8rjr4SarLLc68MCLA9+PdcypEG1jl7SXiwNoAGAsOiLHo7MKMdmHWtqq8CwYAB9k3s0q74ibe8pYmPVwk5YG2VsI7ckf78hVciaIncAOldy0CGw0qqcaXnDpb/uxjKCXryvivwmC8ynDbyWiu1OEhfyGc7iGrFuigEKt0VhmaW3VNecplbcNDNnzbeYVlzSVqGR1GFDwZhAx5pRrFJSUsQ7hfLz2vJ2icPv/EJfDns72PsIBmRZsZ7JCNmK8eqyYQZZ6pcrOerKxhx9tOkqG8Zao2jk/Ii1wLN+5dUZsr0vj7QbhmXl/wcoJVoMD1h8cvRT8dYXZJRnI5T63ZEqq/mdXeMRLTzV0jEsA74LtUOw6ZswSwtGvkQ+Va/v2vEIirzBt3icepU5+PvvJCiJcvIs/Gw3x/PqsoOSK9NQtrMYkp5k/Db+1dWwbyBxbopGY067UJBP/+XJetiupcy94H1HNz8YVlKWGdaEdILCH55T8o5dK3xw4="

notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "pMoYxHfR+7KapRt6h2lHFTq5R6zTTT5YSm2q+0faiyt0lX7VA4qqg1hkxlqdc4r/zmTfXSqpa7Rgy4hZlmv08Q0ZtlpF0fSkSI5Iw1OYKi8Shv0la+JylPCxZHorIkV6BapDj1OSGWtBYVz/aV0aDM7gggs9XyuqVaGE1oCJuyVrhCeyP5I0C0GWfAKQVI0qaLxgSeSeXKCkk2e70eirxwtO8sah+fsz16SJXeda503WXHcyuwHTPgwJJ9i9K0xYvNjsaqTDQ/vAKZcR4c5CyfQYKk89mdxwluSK0xnGljUcigZ1hEzVJsZzd5y6Sx+2pmQW2s2jVV/kGcMOhekbRlThiDyYDWnVOYm4GVPVYWOOvuUQ5Oznsjw2aaWpsejbcGsoqRhpU7dKkql25nSG5SzPSTQQYHlyUdjS7p06RRcRtmh1PRh3RS6P6uXtd+I3wYxiPFCisR+GyyOpsH4gl2Zgq2Sc3QxyF8p53b86EXCvgUdVsGSoIWk1/tOKlsD0RFGNjTd40v8cD3+SLVznBLHSkYJ3wONz5/nmVq7Q0MMwO38knyzB4UKO1V4mycLW4Pmvu/42fi5nJ7Ux/0DGR8ZVSMd8OCpDEEQQth3HwfIIE8MZOYf42GT2SkGDI/QKHtzgxUQQjZNPDEd4C34rQh+WBolv4MDUgkgAl+4+on0="
    on_success: always
    on_failure: always

before_install:
- source scripts/ci/environment.sh
- pip install --upgrade docker-compose
- pip install invoke

install: inv dc.build

script: true
# inv test

after_success:
- ci-tag-build
- hub-push
- hub-updated-readme
# - inv hub.push
# - inv hub.update-readme

deploy:
  provider: releases
  api_key:
    secure: p7a0iK9Ej3+DBhsxDjJKFQuGkpoVtt9FbedOc6mWTvIhxWUTnYoC60w4SUiuWg+A4fbUu+9SZYjFqQowQaFbDJKQfgBiM/DWD65n9FCZgYx9nRZ+fgqrHldKo9nElBMWfWk5KL/RRavB9YKSh+B5yCJAQiEMZn9K5QVL4uuRIXSEs5aLVKsrsNJJR7Wxs5D3UvmbkAxaSJhPfBAj5m1uSkrn6AzOZBJQ+PdnhnU2UhQqAgsx+c4UXJeVBpKbBt+3dWWcAiouQJLiTv0muGjys8UqY3wLcBDSvDPlEWrhhnQiI/8cTGUmvUoFF+sTAh+07/rEyyqC474tb6HF0SmbUWQzQvo96aepFGD0ObE6y0gmJJhc/Tj8vdGPmt8Qq8S2eP31j6wGt4JDLCOsEqGQM/KgknQ8pB03QOAyBUMhYVBTYj68vjeBm0CVH+EoeQLtRiNjXoGhcFnnsQlVwyJjHKIYxLl60Aksvj4ZzzsnnN5KY3mGpA+Q0VIGC7Zs1M3ljgoV+gGYLr6TUndsrt7kJhFoSKhQFBboKF4e2yW/ID/79SGz18aoCI38GjtUYx4WM4m714JZlqBhQUzTl9a/er2aQZBm6sOTxe5QUBsbfuHahjkuU6P+UEgDlgMiI7+WkoTv36uFT25He4B0H+cPDVTAC54jdx+uhGjGL+QQcCg=
  file:
  - images/couchdb-data/couchdb-data.tar.gz
  - images/couchdb-data-preset/couchdb-data-preset.tar.gz
  overwrite: true
  on:
    repo: telephoneorg/docker-kazoo
    tags: true
