version: '2.1'
services:
  kazoo:
    container_name: kazoo
    hostname: kazoo.local
    build:
      context: .
      args:
        KAZOO_VERSION: '4.0'
        KAZOO_BUILD_NUMBER: '8'
    image: "callforamerica/kazoo:${TAG:-latest}"
    env_file: default.env
    ports:
    - "5555:5555"
    - "8000:8000"
    - "19025:19025"
    - "24517:24517"
    networks:
      local:
        aliases:
        - kazoo.local
    depends_on:
      rabbitmq-alpha:
        condition: service_healthy
      rabbitmq-beta:
        condition: service_healthy
      couchdb:
        condition: service_healthy
  rabbitmq-alpha:
    container_name: rabbitmq-alpha
    hostname: rabbitmq-alpha.local
    environment:
      ERLANG_COOKIE: test-cookie
      RABBITMQ_USE_LONGNAME: 'true'
    image: callforamerica/rabbitmq:latest
    networks:
      local:
        aliases:
        - rabbitmq-alpha.local
  rabbitmq-beta:
    container_name: rabbitmq-beta
    hostname: rabbitmq-beta.local
    environment:
      ERLANG_COOKIE: test-cookie
      RABBITMQ_USE_LONGNAME: 'true'
    image: callforamerica/rabbitmq:latest
    networks:
      local:
        aliases:
        - rabbitmq-beta.local
  couchdb:
    container_name: couchdb
    hostname: couchdb.local
    image: callforamerica/couchdb:latest
    environment:
      LOCAL_DEV_CLUSTER: 'true'
      COUCHDB_ADMIN_USER: admin
      COUCHDB_ADMIN_PASS: secret
      ERLANG_COOKIE: test-cookie
    ports:
    - "5984:5984"
    - "5986:5986"
    networks:
      local:
        aliases:
        - couchdb.local
networks:
  local:
