version: '2.3'
services:
  kazoo:
    container_name: kazoo
    hostname: kazoo.local
    build: images/kazoo
    image: telephoneorg/kazoo:${TAG:-latest}
    environment:
      ERLANG_HOSTNAME: long
      ERLANG_COOKIE: test-cookie
      RABBITMQ_HOSTS: rabbitmq.local
      COUCHDB_HOST: couchdb.local
      COUCHDB_USER: admin
      COUCHDB_PASS: secret
      KAZOO_LOG_LEVEL: info
      KAZOO_APPS: blackhole,callflow,cdr,conference,crossbar,doodle,ecallmgr,fax,hangups,hotornot,konami,jonny5,media_mgr,milliwatt,omnipresence,pivot,registrar,reorder,stepswitch,sysconf,tasks,teletype,trunkstore,webhooks
    ports:
    - "5555:5555"
    - "8000:8000"
    - "19025:19025"
    - "24517:24517"
    tmpfs:
    - /tmp
    networks:
      local:
        aliases:
        - kazoo.local
    cap_add:
    - SYS_NICE
    - SYS_RESOURCE
    mem_swappiness: 0
    depends_on:
      rabbitmq:
        condition: service_healthy
      couchdb:
        condition: service_healthy
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq.local
    image: telephoneorg/rabbitmq:latest
    environment:
      ERLANG_HOSTNAME: long
      ERLANG_COOKIE: test-cookie
    tmpfs:
    - /var/lib/rabbitmq/mnesia
    networks:
      local:
        aliases:
        - rabbitmq.local
  couchdb:
    container_name: couchdb
    hostname: couchdb.local
    image: telephoneorg/couchdb:latest
    environment:
      ERLANG_HOSTNAME: long
      COUCHDB_DEV_INIT: 'true'
      COUCHDB_ADMIN_USER: admin
      COUCHDB_ADMIN_PASS: secret
      ERLANG_COOKIE: test-cookie
      COUCHDB_SHARDS: 1
      COUCHDB_LOG_LEVEL: warn
    ports:
    - "5984:5984"
    - "5986:5986"
    tmpfs:
    - /volumes/couchdb/data
    networks:
      local:
        aliases:
        - couchdb.local
    cap_add:
    - SYS_NICE
    - SYS_RESOURCE
networks:
  local:
