version: '2.2'
services:
  kazoo:
    container_name: kazoo
    hostname: kazoo.local
    build: .
    image: telephoneorg/kazoo:${TAG:-latest}
    env:
      ERLANG_HOSTNAME: long
      RABBITMQ_HOSTS: rabbitmq.local
      COUCHDB_HOST: couchdb.local
      KAZOO_LOG_LEVEL: info
      ERLANG_COOKIE: test-cookie
    ports:
    - "5555:5555"
    - "8000:8000"
    - "19025:19025"
    - "24517:24517"
    networks:
      local:
        aliases:
        - kazoo.local
    depends_on:
      rabbitmq:
        condition: service_healthy
      couchdb:
        condition: service_healthy
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq.local
    environment:
      ERLANG_HOSTNAME: long
      ERLANG_COOKIE: test-cookie
    image: telephoneorg/rabbitmq:latest
    networks:
      local:
        aliases:
        - rabbitmq.local
  couchdb:
    container_name: couchdb
    hostname: couchdb.local
    image: telephoneorg/couchdb:latest
    environment:
      ERLANG_HOSTNAME: long
      COUCHDB_DEV_INIT: 'true'
      # COUCHDB_ADMIN_USER: admin
      # COUCHDB_ADMIN_PASS: secret
      ERLANG_COOKIE: test-cookie
    networks:
      local:
        aliases:
        - couchdb.local
networks:
  local:
