apiVersion: v1
kind: ConfigMap
metadata:
  name: kazoo
  labels:
    app: kazoo
    project: telephoneorg
    environment: production
data:
  erlang.hostname: long
  kube.hostname.fix: 'true'
  country: us
  region: east
  couchdb.host: couchdb-lb
  rabbitmq.host: rabbitmq
  kazoo.apps: blackhole,callflow,cdr,conference,crossbar,doodle,ecallmgr,fax,hangups,hotornot,konami,jonny5,media_mgr,milliwatt,omnipresence,pivot,registrar,reorder,stepswitch,sysconf,tasks,teletype,trunkstore,webhooks
  kazoo.log.level: info
  kazoo.log.color: 'true'
  kzutil.kazoo.sounds.tag: '4.1.0'
  kzutil.monster-apps.core.tag: '4.1.56'
  kzutil.monster-apps.custom.tag: '4.2-0'
