apiVersion: v1
kind: ConfigMap
metadata:
  name: kazoo
  labels:
    app: kazoo
    project: telephoneorg
    environment: production
data:
  erlang.hostname: long
  kube.hostname.fix: 'true'
  datacenter: sl
  region: east
  erlang.threads: '64'
  couchdb.host: couchdb-lb
  rabbitmq.hosts: rabbitmq
  kazoo.apps: blackhole,callflow,cdr,conference,crossbar,doodle,ecallmgr,hangups,hotornot,konami,jonny5,media_mgr,milliwatt,omnipresence,pivot,registrar,reorder,stepswitch,sysconf,teletype,trunkstore,webhooks
  kazoo.log.level: info
  kazoo.log.color: 'true'
