apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kazoo
  labels:
    app: kazoo
    project: telephoneorg
    environment: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kazoo
        project: telephoneorg
        environment: production
    spec:
      initContainers:
      - name: kubewait
        image: telephoneorg/kubewait
        imagePullPolicy: IfNotPresent
        args:
        - rabbitmq
        - couchdb
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
      containers:
      - name: kazoo
        image: telephoneorg/kazoo
        imagePullPolicy: Always
        env:
        - name: ERLANG_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: kazoo
              key: erlang.hostname
        - name: KUBE_HOSTNAME_FIX
          valueFrom:
            configMapKeyRef:
              name: kazoo
              key: kube.hostname.fix
        - name: ERLANG_THREADS
          valueFrom:
            configMapKeyRef:
              name: kazoo
              key: erlang.threads
        - name: ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: erlang
              key: erlang.cookie
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: rabbitmq.user
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: rabbitmq.pass
        - name: COUCHDB_HOST
          valueFrom:
            configMapKeyRef:
              name: kazoo
              key: couchdb.host
        - name: COUCHDB_USER
          valueFrom:
            secretKeyRef:
              name: couchdb
              key: couchdb.user
        - name: COUCHDB_PASS
          valueFrom:
            secretKeyRef:
              name: couchdb
              key: couchdb.pass
        - name: REGION
          valueFrom:
            configMapKeyRef:
              name: kazoo
              key: region
        - name: DATACENTER
          valueFrom:
            configMapKeyRef:
              name: kazoo
              key: datacenter
        - name: RABBITMQ_HOSTS
          valueFrom:
            configMapKeyRef:
              name: kazoo
              key: kazoo.amqp.hosts
        - name: KAZOO_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: kazoo
              key: kazoo.log.level
        - name: KAZOO_LOG_COLOR
          valueFrom:
            configMapKeyRef:
              name: kazoo
              key: kazoo.log.color
        - name: KAZOO_APPS
          valueFrom:
            configMapKeyRef:
              name: kazoo
              key: kazoo.apps
        ports:
        - name: crossbar
          containerPort: 8000
        - name: ws-tcp
          containerPort: 5555
        - name: ws-udp
          protocol: UDP
          containerPort: 5555
        - name: fax-smtp
          containerPort: 19025
        - name: media-proxy
          containerPort: 24517
        resources:
          requests:
            cpu: 2
            memory: 2Gi
          limits:
            cpu: 2
            memory: 2Gi
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 160
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 180
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
      restartPolicy: Always
