kind: Service
apiVersion: v1
metadata: 
  name: ecallmgr
spec:
  selector:
    app: kazoo
    kazoo-app: ecallmgr
    project: valuphone
    environment: production
  clusterIP: None
  ports: 
    - name: none
      protocol: TCP
      port: 1