apiVersion: v1
kind: ReplicationController
metadata:
  name: ecallmgr
spec:
  replicas: 1
  selector:
    app: kazoo
    project: valuphone
    kazoo-app: ecallmgr
  template:
    metadata:
      name: ecallmgr
      labels:
        app: kazoo
        otp-release: R15B
        kazoo-app: ecallmgr
        project: valuphone
        role: whapps-server
    spec:
      volumes:
        - name: erlang-cookie-secret
          secret:
            secretName: erlang-cookie
      containers:
        - name: ecallmgr
          image: callforamerica/kazoo
          env:
            - name: KAZOO_APP
              value: ecallmgr
            - name: DATACENTER
              value: sl
            - name: REGION
              value: east 
            - name: KAZOO_LOGLEVEL
              value: info
          imagePullPolicy: Always
          volumeMounts:
            - name: erlang-cookie-secret
              readOnly: true
              mountPath: /etc/secrets/erlang
          resources:
            requests: 
              cpu: 2
              memory: 2G
            # limits:
            #   cpu:
            #   memory:

        # - name: dns
        #   image: callforamerica/go-dnsmasq
      restartPolicy: Always
