apiVersion: v1
kind: ReplicationController
metadata:
  name: ecallmgr
spec:
  replicas: 1
  template:
    metadata:
      name: ecallmgr
      labels:
        app: kazoo
        kazoo-app: ecallmgr
        project: valuphone
        environment: production
    spec:
      volumes:
        - name: erlang-cookie-secret
          secret:
            secretName: erlang-cookie
      containers:
        - name: ecallmgr
          image: callforamerica/kazoo
          env:
            - name: KAZOO_APP
              value: whistle_apps
            - name: KAZOO_LOG_LEVEL
              value: debug
            - name: KUBERNETES_HOSTNAME_FIX
              value: 'true'
            - name: DATACENTER
              value: sl
            - name: REGION
              value: east
          imagePullPolicy: Always
          volumeMounts:
            - name: erlang-cookie-secret
              readOnly: true
              mountPath: /etc/secrets/erlang
          resources:
            requests: 
              cpu: 2
              memory: 2G
            # limits:
            #   cpu:
            #   memory:
      restartPolicy: Always
