kind: Service
apiVersion: v1
metadata: 
  name: kazoo
spec:
  selector:
    app: kazoo
    project: valuphone
    environment: production
  type: ClusterIP
  ports:
  - name: crossbar
    protocol: TCP
    port: 8000
  - name: ws-tcp
    protocol: TCP
    port: 5555
  - name: ws-udp
    protocol: UDP
    port: 5555
  - name: fax-smtp
    protocol: TCP
    port: 19025
  - name: media-proxy
    protocol: TCP
    port: 24517
