apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kazoo
spec:
  replicas: 1
  template:
    metadata:
      name: kazoo
      labels:
        app: kazoo
        project: valuphone
        environment: production
    spec:
      containers:
      - name: kazoo
        image: callforamerica/kazoo:4.0
        env:
        - name: REGION
          valueFrom:
            configMapKeyRef:
              name: environment-config
              key: region
        - name: DATACENTER
          valueFrom:
            configMapKeyRef:
              name: environment-config
              key: datacenter
        - name: KAZOO_APPS
          valueFrom:
            configMapKeyRef:
              name: kazoo-config
              key: kazoo.kazoo-apps
        - name: ERLANG_VM
          valueFrom:
            configMapKeyRef:
              name: kazoo-config
              key: erlang.vm
        - name: ERLANG_THREADS
          valueFrom:
            configMapKeyRef:
              name: kazoo-config
              key: erlang.threads
        - name: KAZOO_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: kazoo-config
              key: kazoo.log-level
        - name: KAZOO_LOG_COLOR
          valueFrom:
            configMapKeyRef:
              name: kazoo-config
              key: kazoo.log-color
        - name: RABBITMQ_HOST_A
          valueFrom:
            configMapKeyRef:
              name: environment-config
              key: rabbitmq.host.a
        - name: RABBITMQ_HOST_B
          valueFrom:
            configMapKeyRef:
              name: environment-config
              key: rabbitmq.host.b
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-creds
              key: rabbitmq.user
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-creds
              key: rabbitmq.pass
        - name: KUBERNETES_HOSTNAME_FIX
          valueFrom:
            configMapKeyRef:
              name: kazoo-config
              key: kubernetes.hostname-fix
        - name: ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: erlang-cookie
              key: erlang.cookie
        - name: COUCHDB_HOST
          valueFrom:
            configMapKeyRef:
              name: environment-config
              key: couchdb.host.balanced
        - name: COUCHDB_USER
          valueFrom:
            secretKeyRef:
              name: couchdb-creds
              key: couchdb.user
        - name: COUCHDB_PASS
          valueFrom:
            secretKeyRef:
              name: couchdb-creds
              key: couchdb.pass
        imagePullPolicy: Always
        ports:
        - name: crossbar
          protocol: TCP
          containerPort: 8000
        - name: ws-tcp
          protocol: TCP
          containerPort: 5555
        - name: ws-udp
          protocol: UDP
          containerPort: 5555
        - name: fax-smtp
          protocol: TCP
          containerPort: 19025
        - name: media-proxy
          protocol: TCP
          containerPort: 24517
        resources:
          requests: 
            cpu: 4
            memory: 4Gi
          limits:
            cpu: 4
            memory: 4Gi
    restartPolicy: Always
