kind: Service
apiVersion: v1
metadata: 
  name: whapps
spec:
  selector:
    app: kazoo
    project: valuphone
    environment: production
    kazoo-app: whistle_apps
  type: ClusterIP
  ports:
    - name: crossbar
      protocol: TCP
      port: 8000
      targetPort: 8000