kind: Pod
apiVersion: v1
metadata:
  name: whapps
  labels:
    app: kazoo
    release: R15B
    kazoo-app: whapps
    role: sip-brain
spec:
  volumes:
    - name: erlang-cookie-secret
      secret:
        secretName: erlang-cookie
    - name: bigcouch-admin-secret
      secret:
        secretName: bigcouch-admin-secret
  containers:
    - name: whapps
      image: callforamerica/kazoo
      env:
        - name: KAZOO_APP
          value: whapps
        - name: DATACENTER
          value: sl
        - name: REGION
          value: east 
        - name: KAZOO_LOGLEVEL
          value: info
      imagePullPolicy: Always
      volumeMounts:
        - name: erlang-cookie-secret
          readOnly: true
          mountPath: /etc/secrets/erlang
        - name: bigcouch-admin-secret
          readOnly: true
          mountPath: /etc/secrets/bigcouch
      ports:
        - name: crossbar
          protocol: TCP
          containerPort: 8000     
    - name: epmd
      image: callforamerica/epmd
    - name: dns
      image: callforamerica/go-dnsmasq
  restartPolicy: Always
