kind: Pod
apiVersion: v1
metadata:
  name: whapps
  labels:
    app: kazoo
    otp-release: R15B
    kazoo-app: whapps
    role: whapps-server
spec:
  volumes:
    - name: erlang-cookie-secret
      secret:
        secretName: erlang-cookie
    - name: bigcouch-admin-secret
      secret:
        secretName: bigcouch-admin-secret
    - name: api-tls
      secret:
        secretName: api-tls
  containers:
    - name: whapps
      image: callforamerica/kazoo
      env:
        - name: KAZOO_APP
          value: whapps
        - name: DATACENTER
          value: sl
        - name: REGION
          value: east 
        - name: KAZOO_LOGLEVEL
          value: info
        - name: TLS_ENABLED
          value: true
      imagePullPolicy: Always
      volumeMounts:
        - name: erlang-cookie-secret
          readOnly: true
          mountPath: /etc/secrets/erlang
        - name: api-tls
          readOnly: true
          mountPath: /etc/secrets/tls
        - name: bigcouch-admin-secret
          readOnly: true
          mountPath: /etc/secrets/bigcouch
      ports:
        - name: crossbar
          protocol: TCP
          containerPort: 8000     
  restartPolicy: Always
