apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: whapps
spec:
  replicas: 1
  template:
    metadata:
      name: whapps
      labels:
        app: kazoo
        kazoo-app: whistle_apps
        project: valuphone
        environment: production
    spec:
      volumes:
        - name: erlang-cookie-secret
          secret:
            secretName: erlang-cookie
      containers:
        - name: whapps
          image: callforamerica/kazoo
          env:
            - name: KAZOO_APP
              value: whistle_apps
            - name: KAZOO_LOG_LEVEL
              value: debug
            - name: KUBERNETES_HOSTNAME_FIX
              value: 'true'
            - name: DATACENTER
              value: sl
            - name: REGION
              value: east
          imagePullPolicy: Always
          volumeMounts:
            - name: erlang-cookie-secret
              readOnly: true
              mountPath: /etc/secrets/erlang
          ports:
            - name: crossbar
              protocol: TCP
              containerPort: 8000
            - name: ws-tcp
              protocol: TCP
              containerPort: 5555
            - name: ws-udp
              protocol: UDP
              containerPort: 5555
          resources:
            requests: 
              cpu: 3
              memory: 3G
            # limits:
            #   cpu:
            #   memory:
      restartPolicy: Always
