kind: Service
apiVersion: v1
metadata: 
  name: whapps
  labels:
    app: kazoo
    kazoo-app: whapps
    opt-release: R15B
    role: whapp-server
spec:
  selector:
    app: kazoo
    project: valuphone
    kazoo-app: whapps
  type: NodePort
  ports:
    - name: crossbar
      protocol: TCP
      port: 8000
      nodePort: 8000